### ISSUE TITLE
Scripts' codes | observations

### ISSUE THREAD

**Issue by Ricky-Tigg** [thiagoojack/packettracer-fedora#13]
Hello. You may prefer to make scripts' codes compact.

### uninstall.sh
```sh
if [ -e /opt/pt ]; then
 (...)
 sudo rm -rf /opt/pt /usr/share/applications/cisco*-pt*.desktop
 sudo xdg-desktop-menu uninstall /usr/share/applications/cisco-pt*.desktop
 (...)
fi
```
### install.sh
- Mention "_www.netacad.com/portal/node/488_" appears to be invalid; produced | "_Access Denied | You don't have permission to access "http://id.cisco.com/app/ciscoid_netacadhttpcanvasauthnetacadcom_1/exkl91gjeATNZmgN95d6/sso/saml?" on this server. (...)_"
- The uninstallation code could refer to _uninstall.sh_ thus avoiding that code:
```sh
if [ -e /opt/pt ]; then
 (...) 
fi
```
- In respect to Packet Tracer, since the **AMD64** architecture is the only one supported for Linux, Fedora user accordingly chooses the appropriate available Fedora release which is **_x86_64_** in order to be able to run that product. RPM package managers, which are` rpm` and `dnf`, automatically select the appropriate architecture IDs for package to be installed via those managers, for instance _noarch_ and _x86_64._ Then those IDs can be omitted in code. Also some expressions can be grouped.
```sh
echo "Installing dependencies"
sudo dnf -y install qt5-qt{multimedia,webengine,networkauth,websockets,webchannel,script,location,svg,speech}
(...)
```

**Comment by Ricky-Tigg** [comment]
### install.sh

Naming scheme of Cisco Packet Tracer for Linux on Cisco's owned [site](https://skillsforall.com/) : `Cisco_Packet_Tracer_<version>_Ubuntu_64bit_<hex-numbers>.deb`.

To keep it simple, covering the **existing** scheme(s). There is **one**, thus:
```sh
# Find Cisco Packet Tracer installer
installer_name=Cisco_Packet_Tracer_*_Ubuntu_64bit_*.deb
path_to_pt=$(find /home -name $installer_name)
```

**Comment by thiagoojack** [comment]
Hi, Ricky! First, thank you so much for your contributions.


> ### uninstall.sh
> 
> ```shell
> if [ -e /opt/pt ]; then
>  (...)
>  sudo rm -rf /opt/pt /usr/share/applications/cisco*-pt*.desktop
>  sudo xdg-desktop-menu uninstall /usr/share/applications/cisco-pt*.desktop
>  (...)
> fi
> ```

This block is from official Cisco's script, but you are right, compact is better.



> * Mention "_[www.netacad.com/portal/node/488](http://www.netacad.com/portal/node/488)_" appears to be invalid; produced | "_Access Denied | You don't have permission to access "http://id.cisco.com/app/ciscoid_netacadhttpcanvasauthnetacadcom_1/exkl91gjeATNZmgN95d6/sso/saml?" on this server. (...)_"

I will replace for https://www.netacad.com/portal/resources/packet-tracer.

**Comment by Ricky-Tigg** [comment]
Or even the **shortest path** to the resource:; https://skillsforall.com/resources/lab-downloads. Here too, login required in order to download resources.

**Comment by Ricky-Tigg** [comment]
### uninstall.sh
A user could delete resources by accident. What follows would lower that risk.
```bash
if [ -e /opt/pt ]; then
(...)
 sudo rm -rf --interactive=once /opt/pt /usr/{share/applications/cisco*-pt*.desktop,local/bin/packettracer}
(...)
fi
```
Yet in name of compactness, l. 12 was integrated to l. 7.

**Comment by Ricky-Tigg** [comment]
As a user could delete resources by accident, what follows would lower that risk.
### uninstall.sh
l. 7
```bash
 sudo rm -rfI /opt/pt /usr/{share/applications/cisco*-pt*.desktop,local/bin/packettracer}
```
Yet in name of compactness, l. 12 was integrated to l. 7.

### install.sh
l. 46
```bash
 sudo rm -rI packettracer
```
User may intend to inspect archive content that could be relevant for improving the code, e.g control.tar.xz's _postinst_ file, or when repetitive code tests require that content to be available.

**Comment by Ricky-Tigg** [comment]
As a user could delete resources by accident, what follows would lower that risk.
### uninstall.sh
l. 7
```bash
 sudo rm -rfI /opt/pt /usr/{share/applications/cisco*-pt*.desktop,local/bin/packettracer}
```
Yet in name of compactness, l. 12 was integrated to l. 7.

### install.sh
l. 46
```bash
 sudo rm -rI packettracer
```
User may intend to inspect archive content that could be relevant for improving the code, e.g. control.tar.xz's _postinst_ file, or fo repetitive code tests that require that content to be available.
