### ISSUE TITLE
Installation script | Multiple messages 'No such file or directory'

### ISSUE THREAD

**Issue by Ricky-Tigg** [thiagoojack/packettracer-fedora#14]
Hello. `sh install.sh` run on Fedora, edition 37. Resulting output relevant for report.
```
gtk-update-icon-cache: No theme index file.
touch: cannot touch '/root/.config/mimeapps.list': No such file or directory
/usr/bin/xdg-mime: line 873: /root/.config/mimeapps.list.new: No such file or directory
```
Once the installation process has ended, `packettracer` triggers a successful opening of the application. Nonetheless, it cannot be determined whether the underlying causes of that output may affect the behaviour or any functionality of that application.

Note: running the script with `sudo` as instructed by _Run sudo bash install.sh and (...)_ in _code_ tab would lead as expected to installation errors caused by the misuse of  `sudo`. So it is dully avoided at least on my system.

**Comment by thiagoojack** [comment]
Hi! :smile: 


> `gtk-update-icon-cache: No theme index file.`

Thats only a warn, it is nothing to be a cause for alarm. http://www.pclinuxos.com/forum/index.php/topic,109423.msg934934.html#msg934934


> touch: cannot touch '/root/.config/mimeapps.list': No such file or directory
> /usr/bin/xdg-mime: line 873: /root/.config/mimeapps.list.new: No such file or directory

You are right, this error is caused by the incorrect use of `sudo` on the `postinst` script inside on the `.deb` package. The `sudo xdg-mime (...)` command should not have the `sudo`. I will try to solve it in the next commit.

**Comment by Ricky-Tigg** [comment]
An investigation at GTK-UPDATE-ICON-C(ACHE(1).'s option `--ignore-theme-index`,` -t` leads me to observe that once applied to _uninstall.sh_ it warning message i avoided; illustration:
```
$ sudo gtk-update-icon-cache -t --force /usr/share/icons/gnome
gtk-update-icon-cache: Cache file created successfully.
```

**Comment by Ricky-Tigg** [comment]
An investigation at GTK-UPDATE-ICON-C(ACHE(1).'s option `--ignore-theme-index`,` -t` leads me to observe that once applied to _uninstall.sh_, that warning message is avoided; illustration:
```
$ sudo gtk-update-icon-cache -t --force /usr/share/icons/gnome
gtk-update-icon-cache: Cache file created successfully.
```

**Comment by Ricky-Tigg** [comment]
An investigation at GTK-UPDATE-ICON-C(ACHE(1).'s option `--ignore-theme-index`,` -t` leads me to observe that once applied to _uninstall.sh_, message _No theme index file_ is avoided; illustration:
```
$ sudo gtk-update-icon-cache -t --force /usr/share/icons/gnome
gtk-update-icon-cache: Cache file created successfully.
```

**Comment by thiagoojack** [comment]
In this case, `postinst` script on `.deb` package also needs to be updated. I used a regular expression for this and I will commit shortly.

**Comment by Ricky-Tigg** [comment]
Before investigating i had reported to upstream via
```
$ dpkg-deb -I Cisco_Packet_Tracer_*_Ubuntu_64bit_*.deb | grep '^ Maintainer'
 Maintainer: Packet Tracer Support <packettracersupport@external.cisco.com>
```
about the message caused by `gtk-update-icon-cache` found in control.tar.xz's postinst
so that  it has the opportunity to fix the code so that we don't have to. Now we know the fix, i shall inform upstream.May it be fixed in next release.

**Comment by Ricky-Tigg** [comment]
Before investigating i had reported to upstream via
```
$ dpkg-deb -I Cisco_Packet_Tracer_*_Ubuntu_64bit_*.deb | grep '^ Maintainer'
 Maintainer: Packet Tracer Support <packettracersupport@external.cisco.com>
```
about the message caused by `gtk-update-icon-cache` found in control.tar.xz's _postinst_ so that  it has the opportunity to fix the code so that we don't have to. Now we know the fix, i shall inform upstream of that. May it be fixed in next release.

**Comment by thiagoojack** [comment]
Great job!
Now let's hope that the upstream accepts the proposal.
