### ISSUE TITLE
Install script requires binutils

### ISSUE THREAD

**Issue by cgryba** [thiagoojack/packettracer-fedora#22]
Hello,

I noticed a small oversight in the install script which affects at least Fedora 38 Workstation.

A fresh install of Fedora 38 Workstation cannot run install.sh without first installing package binutils.

Without binutils, install.sh cannot unarchive: output: "install.sh: line 32: ar: command not found".

After installing binutils, ar is available and the install script succeeds.

Thank you for your work on this! Much appreciated.

Kindest regards,

Conrad Gryba

**Comment by thiagoojack** [comment]
Hello! Thanks for your feedback! I solved it in #23 because of you. Thank you so much!
