### ISSUE TITLE
After install i'm not able to add modules to routers etc.

### ISSUE THREAD

**Issue by TomFang1** [thiagoojack/packettracer-fedora#25]
I've recently installed packet tracer 8.2.1 with this script and everything is working except the modules neither I'm able to add modules nor I'm able to remove modules from previous configured routers. I currently use Nobara 38, which is based on Fedora 38. I also don't have a log, because i don't know where i could get one.

**Comment by TomFang1** [comment]
Update: I could add Modules manually with the Workspace list. So only dragging them visually into the router isn't working.

**Comment by thiagoojack** [comment]
You're right! I don't know what exactly is the cause, but looking for the `ldd` output I can see a dependency that not satisfied. Look:
```
$ ldd /opt/pt/bin/PacketTracer | grep not
	libcrypto.so.1.1 => not found
	libcrypto.so.1.1 => not found
```
Try in you system and show me if you have too the same issue.

**Comment by TomFang1** [comment]
![Bildschirmfoto vom 2023-05-05 16-17-12](https://user-images.githubusercontent.com/80842080/236483745-5230595c-587b-4fae-b990-d332f91d5790.png)

Nope, i didn't face that issue and libcrypto is installed

**Comment by thiagoojack** [comment]
I found the problem on `journalctl -xe` output.
```
May 05 11:14:32 deskstation gnome-shell[1795]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x800027 specified for 0x800025.
May 05 11:14:47 deskstation gnome-shell[1795]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x800027 specified for 0x80003f.
May 05 11:14:48 deskstation gnome-shell[1795]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x800027 specified for 0x80004c.
May 05 11:14:50 deskstation gnome-shell[1795]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x800027 specified for 0x800059.
```
Probably, the problem is causing by some interaction of packet tracer with Wayland.

**Comment by thiagoojack** [comment]
Sorry, I meant `Window Manager`. For some reason, Packet Tracer can not interact effectively with `gnome-shell`.
