### ISSUE TITLE
fedora 38 faild

### ISSUE THREAD

**Issue by View-my-Git-Lab-krafi** [thiagoojack/packettracer-fedora#26]
`
❯ cp ~/Downloads/CiscoPacketTracer_821_Ubuntu_64bit.deb ~/                       

 ❯sudo ./install.sh                                       

The Packet Tracer installer was found at:
/home/krafi.info/Downloads/CiscoPacketTracer_821_Ubuntu_64bit.deb
/home/krafi.info/CiscoPacketTracer_821_Ubuntu_64bit.deb

Removing old version of Packet Tracer from /opt/pt
Installing dependencies
Last metadata expiration check: 1:28:03 ago on Sun 28 May 2023 05:40:11 PM +06.
Package binutils-2.39-9.fc38.x86_64 is already installed.
Package qt5-qtmultimedia-5.15.9-1.fc38.x86_64 is already installed.
Package qt5-qtwebengine-5.15.12-5.fc38.x86_64 is already installed.
Package qt5-qtnetworkauth-5.15.9-1.fc38.x86_64 is already installed.
Package qt5-qtwebchannel-5.15.9-1.fc38.x86_64 is already installed.
Package qt5-qtscript-5.15.9-1.fc38.x86_64 is already installed.
Package qt5-qtlocation-5.15.9-1.fc38.x86_64 is already installed.
Package qt5-qtsvg-5.15.9-2.fc38.x86_64 is already installed.
Package qt5-qtspeech-5.15.9-1.fc38.x86_64 is already installed.
Dependencies resolved.
==============================================================================================================================================================================================
 Package                                            Architecture                             Version                                          Repository                                 Size
==============================================================================================================================================================================================
Installing:
 qt5-qtwebsockets                                   x86_64                                   5.15.9-1.fc38                                    updates                                    87 k

Transaction Summary
==============================================================================================================================================================================================
Install  1 Package

Total download size: 87 k
Installed size: 272 k
Downloading Packages:
qt5-qtwebsockets-5.15.9-1.fc38.x86_64.rpm                                                                                                                     126 kB/s |  87 kB     00:00    
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                          54 kB/s |  87 kB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                      1/1 
  Installing       : qt5-qtwebsockets-5.15.9-1.fc38.x86_64                                                                                                                                1/1 
  Running scriptlet: qt5-qtwebsockets-5.15.9-1.fc38.x86_64                                                                                                                                1/1 
  Verifying        : qt5-qtwebsockets-5.15.9-1.fc38.x86_64                                                                                                                                1/1 

Installed:
  qt5-qtwebsockets-5.15.9-1.fc38.x86_64                                                                                                                                                       

Complete!
Extracting files
no entry /home/krafi.info/CiscoPacketTracer_821_Ubuntu_64bit.deb in archive
tar: packettracer/control.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: packettracer/data.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
cp: cannot stat 'packettracer/usr': No such file or directory
cp: cannot stat 'packettracer/opt': No such file or directory
sed: can't read /usr/share/applications/cisco-pt.desktop: No such file or directory
sed: can't read ./packettracer/postinst: No such file or directory
sed: can't read ./packettracer/postinst: No such file or directory
sudo: ./packettracer/postinst: command not found
`

**Comment by thiagoojack** [comment]
Hi!
Are you using bash?

**Comment by Skargas** [comment]
when you unpack the .deb package, on the second command "tar -xvf data.tar.xz" not all files are there, on the next step when you do "vim /usr/share/applications/cisco-pt.desktop" there is no applications folder, under usr/share/ there are only 2 folders: icons and mime.

This is why it fails.

**Comment by thiagoojack** [comment]
Today I tried to install Packet Tracer with this script, and have no problem. Watch this video if you have any doubts:
[Packet Tracer 8.2.1 Fedora 38 installation via script](https://www.youtube.com/watch?v=g9TITCwhOxI)
