### ISSUE TITLE
Name Change of Files!

### ISSUE THREAD

**Issue by VshadowTX** [thiagoojack/packettracer-fedora#30]
Need correct new name on install.sh line 12  installer_name_2=Packet_Tracer*.deb

old name: CiscoPacketTracer*Ubuntu_64bit.deb
new name: Packet_Tracer821_amd64_signed.deb

Only with this change it works very well in Fedora 38, excellent work in its Script.

**Comment by thiagoojack** [comment]
Thank you, my friend!
