### ISSUE TITLE
Empty unnessary space at end of line 62

### ISSUE THREAD

**Issue by PranavBhattarai** [thiagoojack/packettracer-fedora#34]
Not a major issue though. The script should work fine. Just need some cleaning in line 62. :-D 
![image](https://github.com/thiagoojack/packettracer-fedora/assets/32763112/db4e8698-5f73-4a90-879a-b27dda2b0039)

**Comment by osalbahr** [comment]
Would you be interested in making a PR?

**Comment by Ludo-code** [comment]
Opened pull request for fix
