### ISSUE TITLE
No icon for all mime type for packettracer

### ISSUE THREAD

**Issue by Ludo-code** [thiagoojack/packettracer-fedora#38]
When installing and using it, the pkt and other file created with packet tracer have no icon...

for exemple : 

![image](https://github.com/thiagoojack/packettracer-fedora/assets/56892223/d7691365-a700-42c5-9a1d-b3f2ed116fc2)

**Comment by thiagoojack** [comment]
Which DE are you using? I'm using Fedora with GNOME and I've never seen this.

**Comment by Ludo-code** [comment]
Actually using Dolphin on fedora spin KDE maybe it's just an issue related to KDE...

**Comment by PranavBhattarai** [comment]
I had to google search **.pkt** file extension icons. Normally it should look like this. 
![Screenshot from 2024-01-20 11-43-30](https://github.com/thiagoojack/packettracer-fedora/assets/32763112/ec8eadb6-7dbc-485b-ae06-693a998c595a)

But in my **Fedora 39 Workstation Edition** which have **GNOME 45.3** as a desktop environment, I get to see this:
![image](https://github.com/thiagoojack/packettracer-fedora/assets/32763112/d37658a7-69d0-4d2b-a156-c80cea7a7b63)

**Comment by Ludo-code** [comment]
I have reproduced the bug with a clean install of fedora.

I will try to install the latest version of packet tracer on ubuntu to check if it's not a problem of the new deb package

**Comment by Ludo-code** [comment]
I think @thiagoojack have the icon because he have installed an older version of packet tracer and icon remain in file...

**Comment by Ludo-code** [comment]
I'm confirming the same issue on ubutun 22.03 and 23.10...
![image](https://github.com/thiagoojack/packettracer-fedora/assets/56892223/588da6d2-2961-4cf0-ad87-b90daa88aa5f)

**Comment by thiagoojack** [comment]
It became clear that problem depend on the upstream.
