### ISSUE TITLE
Name matching problem

### ISSUE THREAD

**Issue by Belkata** [thiagoojack/packettracer-fedora#40]
The script was unable to find the package with this name:
CiscoPacketTracer822_amd64_signed.deb

**Comment by Belkata** [comment]
I added an underscore after "Cisco" after I looked through the script and it worked:
Cisco_PacketTracer822_amd64_signed.deb
I would suggest some other way of finding the package, but I am not sure how that would be possible.

**Comment by sanquin0ton** [comment]
> I added an underscore after "Cisco" after I looked through the script and it worked: Cisco_PacketTracer822_amd64_signed.deb I would suggest some other way of finding the package, but I am not sure how that would be possible.

through my testing the best way to fix this is to add the following line and add
intstaller_name_4=CiscoPacketTracer*_amd64_signed.deb
then add it to the find.

**Comment by thiagoojack** [comment]
Thank you for report this issue.
