### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by b4j0n1tz** [thiagoojack/packettracer-fedora#44]
Hi, I have tested the repository and everything is fine, but I have a question.

When I run the packet tracer application it creates a folder with the name "pt" in the /home/user directory.
I would like to know how I can change the Packet Tracer configuration to put that folder somewhere else on my computer.
Do you know what I could do to change the location of the "pt" folder?

Thanks.

**Comment by thiagoojack** [comment]
Hi! You need to go to _Options > Preferences > Administrative tab_ and `User Folder`.
![change-pt-home](https://github.com/thiagoojack/packettracer-fedora/assets/5920212/62d5f793-55df-44fe-b5e9-a6fd4daa809e)

**Comment by b4j0n1tz** [comment]
Thanks!!!
