### ISSUE TITLE
Works on Fedora 40

### ISSUE THREAD

**Issue by usmanhdsidiq** [thiagoojack/packettracer-fedora#50]
Nice!
It runs fine on Fedora 40 kernel 6.8.7-300
Cisco Packet Tracer 8.2.2
Great thanks

![image](https://github.com/thiagoojack/packettracer-fedora/assets/141495494/40d79e0c-7799-4bb0-bf2a-f53400b24c23)

**Comment by thiagoojack** [comment]
Thank you, bro!

**Comment by Yayin-Vashist** [comment]
Thank you @grepjack for making this repository! I was trying to do the same for the past few hours.
